Vagrant.configure("2") do |config|
	config.vagrant.plugins = [ "vagrant-vbguest" ]

  config.vm.define "jumphost" do |box|
	box.vm.box = "bento/ubuntu-22.04"
	box.vm.hostname = "jumphost"
	box.vm.network "private_network", ip: "192.168.56.11"
	box.vm.provision "shell", path: "jumphost.sh"
	end
end