Vagrant.configure("2") do |config|
  config.vm.define "jumphost" do |box|
	jumphost.vm.box = "bento/ubuntu-22.04"
	jumphost.vm.hostname = "jumphost"
	jumphost.vm.network "private_network", ip: "192.168.56.11"
	jumphost.vm.provision :shell, path: "jumphost.sh"
	  end
	end